### ISSUE TITLE
NPE in DML

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/Infrastructure#19]
java.lang.NullPointerException: null
	at eu.qualimaster.dataManagement.sources.ReplayMechanism.connect(ReplayMechanism.java:267) ~[classes/:na]
	at tests.eu.qualimaster.storm.TestSrc.connect(TestSrc.java:46) ~[classes/:na]
	at tests.eu.qualimaster.storm.Source.open(Source.java:64) ~[classes/:na]
	at backtype.storm.daemon.executor$fn__316$fn__331.invoke(executor.clj:716) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.util$async_loop$fn__296.invoke(util.clj:473) ~[storm-core-0.9.5.jar:0.9.5]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_66]

**Comment by eichelbe** [comment]
uups. wrong replay
